rails-vue-todo-app/config/routes.rb
Rails.application.routes.draw do
  root to: 'todos#index'
  resources :todos, only: [:index, :create, :update, :destroy]
end

rails-vue-todo-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-vue-todo-app/app/models/todo.rb
class Todo < ApplicationRecord
  validates :text, length: { minimum: 5, message: 'must be at least 5 characters' }, uniqueness: { message: 'must be unique' }
end

rails-vue-todo-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails-vue-todo-app/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all.order(text: :asc)
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:text, :completed)
    end
end

rails-vue-todo-app/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-vue-todo-app/app/helpers/todos_helper.rb
module TodosHelper
end

rails-vue-todo-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vue-Rails Todo App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'app', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

rails-vue-todo-app/app/views/todos/_form.html.erb
<%= content_tag :div,
  id: 'todo-form',
  data: {
    todo: todo.to_json(except: [:created_at, :updated_at])
  } do %>

<label>Name</label>
<input type="text" v-model="todo.text" />

<label>Completed?</label>
<input type="checkbox" v-model="todo.completed" />

<div>
  <button v-on:click="saveTodo">Save Todo</button>
</div>

<% end %>

rails-vue-todo-app/app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

rails-vue-todo-app/app/views/todos/index.html.erb
<div class="row">
  <h1 class="page-heading col">Hacker Todos</h1>
</div>

<div id='vue-todo-page'>
  <todo-page :todos="<%= @todos.to_json %>"></todo-page> 
</div>

rails-vue-todo-app/app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

rails-vue-todo-app/app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @todo.text %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @todo.completed %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>